-- HORDE MONSTER CONFIG
-- Vortex-style Lua globals: edit values below; no tables are required.

-- Global Weapon Damage
GLOBAL_DAMAGE_MELEE                              = 7
GLOBAL_DAMAGE_SLAM                               = 30
GLOBAL_DAMAGE_PROBOSCIS                          = 7
GLOBAL_DAMAGE_BLASTER                            = 5
GLOBAL_DAMAGE_BLASTER2                           = 7
GLOBAL_DAMAGE_BLASTER_BOLT                       = 8
GLOBAL_DAMAGE_BLUEBLASTER                        = 5
GLOBAL_DAMAGE_HYPERBLASTER                       = 6
GLOBAL_DAMAGE_SHOTGUN                            = 1
GLOBAL_DAMAGE_MACHINEGUN                         = 3
GLOBAL_DAMAGE_GRENADE                            = 18
GLOBAL_DAMAGE_ROCKET                             = 22
GLOBAL_DAMAGE_HEAT                               = 20
GLOBAL_DAMAGE_RAILGUN                            = 25
GLOBAL_DAMAGE_BFG                                = 25
GLOBAL_DAMAGE_IONRIPPER                          = 6
GLOBAL_DAMAGE_FLECHETTE                          = 4
GLOBAL_DAMAGE_PLASMA                             = 12
GLOBAL_DAMAGE_TRACKER                            = 7
GLOBAL_DAMAGE_HEATBEAM                           = 5
GLOBAL_DAMAGE_DABEAM                             = 5
GLOBAL_DAMAGE_LIGHTNING                          = 5
GLOBAL_DAMAGE_FIREBALL                           = 12
GLOBAL_DAMAGE_BOLT                               = 14

-- Global Weapon Speed
GLOBAL_SPEED_BLASTER                             = 1000
GLOBAL_SPEED_BLASTER2                            = 1000
GLOBAL_SPEED_BLASTER_BOLT                        = 1000
GLOBAL_SPEED_BLUEBLASTER                         = 1000
GLOBAL_SPEED_HYPERBLASTER                        = 1000
GLOBAL_SPEED_GRENADE                             = 600
GLOBAL_SPEED_ROCKET                              = 650
GLOBAL_SPEED_HEAT                                = 650
GLOBAL_SPEED_BFG                                 = 400
GLOBAL_SPEED_IONRIPPER                           = 1000
GLOBAL_SPEED_FLECHETTE                           = 1150
GLOBAL_SPEED_PLASMA                              = 700
GLOBAL_SPEED_TRACKER                             = 500
GLOBAL_SPEED_FIREBALL                            = 600
GLOBAL_SPEED_BOLT                                = 600

-- Global Weapon Radius
GLOBAL_RADIUS_GRENADE                            = 140
GLOBAL_RADIUS_ROCKET                             = 120
GLOBAL_RADIUS_HEAT                               = 140
GLOBAL_RADIUS_BFG                                = 450
GLOBAL_RADIUS_PLASMA                             = 120
GLOBAL_RADIUS_TRACKER                            = 140
GLOBAL_RADIUS_FIREBALL                           = 120

-- ============================================================================
-- BOSS-ONLY WEAPON DAMAGE OVERRIDES
-- Applied ONLY to IS_BOSS instances. Key form: MONSTER_<TYPE>_BOSS_DAMAGE_<WEAPON>.
-- These are EXACT final values: they ignore DAMAGE_SCALE and the DAMAGE_MAX caps, so a
-- boss can hit harder than its normal counterpart. A weapon key only has an effect if that
-- monster's attack actually reads it through the M_*_DMG path -- e.g. the tank family's
-- heat-seeker reads ROCKET (not HEAT), and supertank rocket/bullet damage is hardcoded.
-- ============================================================================

-- Tank Commander (blaster attack fires a blaster2 projectile but reads the BLASTER key;
-- the punch/strike is a SLAM radius hit)
MONSTER_TANK_COMMANDER_BOSS_DAMAGE_ROCKET        = 110
MONSTER_TANK_COMMANDER_BOSS_DAMAGE_BLASTER       = 45
MONSTER_TANK_COMMANDER_BOSS_DAMAGE_SLAM          = 175

-- Tank 64 (heat-seeker reads the ROCKET key; the punch/strike is a SLAM radius hit.
-- Without this, the boss slam falls back to the global SLAM=30 and feels very weak.)
MONSTER_TANK_64_BOSS_DAMAGE_ROCKET               = 120
MONSTER_TANK_64_BOSS_DAMAGE_SLAM                 = 175

-- Runnertank
MONSTER_RUNNERTANK_BOSS_DAMAGE_ROCKET            = 90
MONSTER_RUNNERTANK_BOSS_DAMAGE_PLASMA            = 20
MONSTER_RUNNERTANK_BOSS_DAMAGE_RAILGUN           = 70
MONSTER_RUNNERTANK_BOSS_DAMAGE_SLAM              = 90

-- Carrier (rockets are heat-seekers -> HEAT key)
MONSTER_CARRIER_BOSS_DAMAGE_HEAT                 = 80
MONSTER_CARRIER_BOSS_DAMAGE_GRENADE              = 70
MONSTER_CARRIER_BOSS_DAMAGE_MACHINEGUN           = 10

-- Carrier Mini
MONSTER_CARRIER_MINI_BOSS_DAMAGE_HEAT            = 50
MONSTER_CARRIER_MINI_BOSS_DAMAGE_ROCKET          = 45
MONSTER_CARRIER_MINI_BOSS_DAMAGE_GRENADE         = 45
MONSTER_CARRIER_MINI_BOSS_DAMAGE_MACHINEGUN      = 8

-- Widow2
MONSTER_WIDOW2_BOSS_DAMAGE_TRACKER               = 40
MONSTER_WIDOW2_BOSS_DAMAGE_HEATBEAM              = 20

-- Boss2
MONSTER_BOSS2_BOSS_DAMAGE_ROCKET                 = 90
MONSTER_BOSS2_BOSS_DAMAGE_MACHINEGUN             = 10
MONSTER_BOSS2_BOSS_DAMAGE_BLASTER_BOLT           = 22

-- Boss2 64
MONSTER_BOSS2_64_BOSS_DAMAGE_ROCKET              = 90
MONSTER_BOSS2_64_BOSS_DAMAGE_MACHINEGUN          = 10
MONSTER_BOSS2_64_BOSS_DAMAGE_BLASTER_BOLT        = 22

-- Boss2 Mini
MONSTER_BOSS2_MINI_BOSS_DAMAGE_ROCKET            = 70
MONSTER_BOSS2_MINI_BOSS_DAMAGE_MACHINEGUN        = 9
MONSTER_BOSS2_MINI_BOSS_DAMAGE_BLASTER_BOLT      = 18

-- Supertank (rocket/bullet are hardcoded; HEAT + GRENADE are configurable)
MONSTER_SUPERTANK_BOSS_DAMAGE_HEAT               = 90
MONSTER_SUPERTANK_BOSS_DAMAGE_GRENADE            = 70

-- Supertankkl
MONSTER_SUPERTANKKL_BOSS_DAMAGE_HEAT             = 110
MONSTER_SUPERTANKKL_BOSS_DAMAGE_GRENADE          = 85

-- Makron
MONSTER_MAKRON_BOSS_DAMAGE_BFG                   = 80
MONSTER_MAKRON_BOSS_DAMAGE_RAILGUN               = 75
MONSTER_MAKRON_BOSS_DAMAGE_BLASTER               = 40

-- Makronkl
MONSTER_MAKRONKL_BOSS_DAMAGE_BFG                 = 90
MONSTER_MAKRONKL_BOSS_DAMAGE_RAILGUN             = 80
MONSTER_MAKRONKL_BOSS_DAMAGE_BLASTER             = 45

-- Jorg
MONSTER_JORG_BOSS_DAMAGE_BFG                     = 90
MONSTER_JORG_BOSS_DAMAGE_PLASMA                  = 20

-- Boss5
MONSTER_BOSS5_BOSS_DAMAGE_HEAT                   = 90

-- Shambler (lightning beam fires once per cast on 3 cast frames -> per-cast LIGHTNING key)
MONSTER_SHAMBLER_BOSS_DAMAGE_LIGHTNING           = 25
MONSTER_SHAMBLERKL_BOSS_DAMAGE_LIGHTNING         = 30

-- Chickkl (Hell Maidens boss trio; each volley is 4 heat-seeking bolts, so the boss keeps the
-- old per-bolt 23 while normal field chickkls drop to 15)
MONSTER_CHICKKL_BOSS_DAMAGE_PLASMA               = 23

-- Guardian
MONSTER_GUARDIAN_BOSS_DAMAGE_BLASTER             = 35
MONSTER_GUARDIAN_BOSS_DAMAGE_DABEAM              = 45
MONSTER_GUARDIAN_BOSS_DAMAGE_IONRIPPER           = 40

-- PSX Guardian (bypasses the DAMAGE_MAX_BLASTER cap below)
MONSTER_PSXGUARDIAN_BOSS_DAMAGE_BLASTER          = 30
MONSTER_PSXGUARDIAN_BOSS_DAMAGE_HEAT             = 70

-- Turret
MONSTER_TURRET_HEALTH                            = 100
MONSTER_TURRET_ARMOR_POWER                       = 40
MONSTER_TURRET_ARMOR_TYPE                        = 0
MONSTER_TURRET_DAMAGE_SCALE                      = 0.6

-- Soldier Light
MONSTER_SOLDIER_LIGHT_HEALTH                     = 40
MONSTER_SOLDIER_LIGHT_POWER_ARMOR_POWER          = 20
MONSTER_SOLDIER_LIGHT_POWER_ARMOR_TYPE           = 0
MONSTER_SOLDIER_LIGHT_DAMAGE_SCALE               = 0.6

-- Soldier
MONSTER_SOLDIER_HEALTH                           = 50
MONSTER_SOLDIER_POWER_ARMOR_POWER                = 30
MONSTER_SOLDIER_POWER_ARMOR_TYPE                 = 0
MONSTER_SOLDIER_DAMAGE_SCALE                     = 1
MONSTER_SOLDIER_DAMAGE_BLASTER                   = 5
MONSTER_SOLDIER_DAMAGE_MAX_BLASTER               = 5
MONSTER_SOLDIER_ADDON_DAMAGE_BLASTER             = 0
MONSTER_SOLDIER_DAMAGE_BLUEBLASTER               = 1
MONSTER_SOLDIER_DAMAGE_IONRIPPER                 = 5
MONSTER_SOLDIER_DAMAGE_MACHINEGUN                = 2
MONSTER_SOLDIER_DAMAGE_SHOTGUN                   = 2

-- Soldier Ss
MONSTER_SOLDIER_SS_HEALTH                        = 40
MONSTER_SOLDIER_SS_ARMOR_POWER                   = 30
MONSTER_SOLDIER_SS_ARMOR_TYPE                    = 0
MONSTER_SOLDIER_SS_DAMAGE_SCALE                  = 1

-- Soldier Hypergun
MONSTER_SOLDIER_HYPERGUN_HEALTH                  = 95
MONSTER_SOLDIER_HYPERGUN_POWER_ARMOR_POWER       = 40
MONSTER_SOLDIER_HYPERGUN_POWER_ARMOR_TYPE        = "screen"
MONSTER_SOLDIER_HYPERGUN_DAMAGE_SCALE            = 0.8

-- Soldier Ripper
MONSTER_SOLDIER_RIPPER_HEALTH                    = 70
MONSTER_SOLDIER_RIPPER_POWER_ARMOR_POWER         = 40
MONSTER_SOLDIER_RIPPER_POWER_ARMOR_TYPE          = "screen"
MONSTER_SOLDIER_RIPPER_DAMAGE_SCALE              = 0.3

-- Soldier Lasergun
MONSTER_SOLDIER_LASERGUN_HEALTH                  = 40
MONSTER_SOLDIER_LASERGUN_POWER_ARMOR_POWER       = 40
MONSTER_SOLDIER_LASERGUN_POWER_ARMOR_TYPE        = "screen"
MONSTER_SOLDIER_LASERGUN_DAMAGE_SCALE            = 0.25

-- Infantry
MONSTER_INFANTRY_HEALTH                          = 150
MONSTER_INFANTRY_POWER_ARMOR_POWER               = 100
MONSTER_INFANTRY_POWER_ARMOR_TYPE                = "shield"
MONSTER_INFANTRY_DAMAGE_SCALE                    = 0.7
MONSTER_INFANTRY_DAMAGE_BLASTER2                 = 6
MONSTER_INFANTRY_DAMAGE_GRENADE                  = 50
MONSTER_INFANTRY_DAMAGE_MACHINEGUN               = 3

-- Infantry Vanilla
MONSTER_INFANTRY_VANILLA_HEALTH                  = 130
MONSTER_INFANTRY_VANILLA_ARMOR_POWER             = 50
MONSTER_INFANTRY_VANILLA_ARMOR_TYPE              = "combat"
MONSTER_INFANTRY_VANILLA_DAMAGE_SCALE            = 1
MONSTER_INFANTRY_VANILLA_DAMAGE_GRENADE          = 40
MONSTER_INFANTRY_VANILLA_DAMAGE_MACHINEGUN       = 3
MONSTER_INFANTRY_VANILLA_DAMAGE_MAX_MACHINEGUN   = 3
MONSTER_INFANTRY_VANILLA_ADDON_DAMAGE_MACHINEGUN = 0

-- Gunner
MONSTER_GUNNER_HEALTH                            = 175
MONSTER_GUNNER_POWER_ARMOR_POWER                 = 85
MONSTER_GUNNER_POWER_ARMOR_TYPE                  = "shield"
MONSTER_GUNNER_DAMAGE_SCALE                      = 1
MONSTER_GUNNER_DAMAGE_GRENADE                    = 40
MONSTER_GUNNER_DAMAGE_IONRIPPER                  = 5

-- Gunner Vanilla
MONSTER_GUNNER_VANILLA_HEALTH                    = 175
MONSTER_GUNNER_VANILLA_POWER_ARMOR               = 85
MONSTER_GUNNER_VANILLA_POWER_ARMOR_TYPE          = "combat"
MONSTER_GUNNER_VANILLA_DAMAGE_SCALE              = 0.5
MONSTER_GUNNER_VANILLA_DAMAGE_GRENADE            = 40
MONSTER_GUNNER_VANILLA_DAMAGE_MACHINEGUN         = 3
MONSTER_GUNNER_VANILLA_DAMAGE_MAX_MACHINEGUN     = 3
MONSTER_GUNNER_VANILLA_ADDON_DAMAGE_MACHINEGUN   = 0

-- Medic
MONSTER_MEDIC_HEALTH                             = 110
MONSTER_MEDIC_ARMOR_POWER                        = 120
MONSTER_MEDIC_ARMOR_TYPE                         = "combat"
MONSTER_MEDIC_DAMAGE_SCALE                       = 1.2
MONSTER_MEDIC_DAMAGE_BLASTER2                    = 6
MONSTER_MEDIC_DAMAGE_MAX_BLASTER2                = 6
MONSTER_MEDIC_ADDON_DAMAGE_BLASTER2              = 0
MONSTER_MEDIC_DAMAGE_BOLT                        = 30

-- Medic Commander
MONSTER_MEDIC_COMMANDER_HEALTH                   = 300
MONSTER_MEDIC_COMMANDER_POWER_ARMOR_POWER        = 0
MONSTER_MEDIC_COMMANDER_DAMAGE_SCALE             = 1.5
MONSTER_MEDIC_COMMANDER_DAMAGE_BLASTER           = 6
MONSTER_MEDIC_COMMANDER_DAMAGE_MAX_BLASTER       = 6
MONSTER_MEDIC_COMMANDER_ADDON_DAMAGE_BLASTER     = 0
MONSTER_MEDIC_COMMANDER_DAMAGE_BLASTER2          = 6
MONSTER_MEDIC_COMMANDER_DAMAGE_MAX_BLASTER2      = 6
MONSTER_MEDIC_COMMANDER_ADDON_DAMAGE_BLASTER2    = 0
MONSTER_MEDIC_COMMANDER_DAMAGE_BOLT              = 30
MONSTER_MEDIC_COMMANDER_DAMAGE_MAX_BOLT          = 30
MONSTER_MEDIC_COMMANDER_ADDON_DAMAGE_BOLT        = 0

-- Guncmdr
MONSTER_GUNCMDR_HEALTH                           = 325
MONSTER_GUNCMDR_POWER_ARMOR_POWER                = 120
MONSTER_GUNCMDR_POWER_ARMOR_TYPE                 = "shield"
MONSTER_GUNCMDR_DAMAGE_SCALE                     = 1
MONSTER_GUNCMDR_DAMAGE_GRENADE                   = 25
MONSTER_GUNCMDR_DAMAGE_MELEE                     = 30

-- Guncmdr Vanilla
MONSTER_GUNCMDR_VANILLA_HEALTH                   = 200
MONSTER_GUNCMDR_VANILLA_POWER_ARMOR_POWER        = 80
MONSTER_GUNCMDR_VANILLA_POWER_ARMOR_TYPE         = "shield"
MONSTER_GUNCMDR_VANILLA_DAMAGE_SCALE             = 1
MONSTER_GUNCMDR_VANILLA_DAMAGE_FLECHETTE         = 4
MONSTER_GUNCMDR_VANILLA_DAMAGE_MAX_FLECHETTE     = 4
MONSTER_GUNCMDR_VANILLA_ADDON_DAMAGE_FLECHETTE   = 0
MONSTER_GUNCMDR_VANILLA_DAMAGE_GRENADE           = 20
MONSTER_GUNCMDR_VANILLA_DAMAGE_MELEE             = 30

-- Guncmdrkl
MONSTER_GUNCMDRKL_HEALTH                         = 500
MONSTER_GUNCMDRKL_POWER_ARMOR_POWER              = 180
MONSTER_GUNCMDRKL_POWER_ARMOR_TYPE               = "shield"
MONSTER_GUNCMDRKL_HEALTH_SCALE                   = 1
MONSTER_GUNCMDRKL_DAMAGE_SCALE                   = 1.5
MONSTER_GUNCMDRKL_DAMAGE_MAX_FLECHETTE           = 4
MONSTER_GUNCMDRKL_ADDON_DAMAGE_FLECHETTE         = 0
MONSTER_GUNCMDRKL_DAMAGE_GRENADE                 = 40
MONSTER_GUNCMDRKL_DAMAGE_MACHINEGUN              = 3
MONSTER_GUNCMDRKL_DAMAGE_MAX_MACHINEGUN          = 3
MONSTER_GUNCMDRKL_ADDON_DAMAGE_MACHINEGUN        = 0
MONSTER_GUNCMDRKL_DAMAGE_MELEE                   = 22

-- Gladiator
MONSTER_GLADIATOR_HEALTH                         = 140
MONSTER_GLADIATOR_ARMOR_POWER                    = 120
MONSTER_GLADIATOR_ARMOR_TYPE                     = "combat"
MONSTER_GLADIATOR_DAMAGE_SCALE                   = 2.5
MONSTER_GLADIATOR_DAMAGE_MELEE                   = 25
MONSTER_GLADIATOR_DAMAGE_MAX_MELEE               = 25
MONSTER_GLADIATOR_ADDON_DAMAGE_MELEE             = 0
MONSTER_GLADIATOR_DAMAGE_RAILGUN                 = 50
MONSTER_GLADIATOR_DAMAGE_MAX_RAILGUN             = 50
MONSTER_GLADIATOR_ADDON_DAMAGE_RAILGUN           = 0
MONSTER_GLADIATOR_DAMAGE_TRACKER                 = 16

-- Gladb
MONSTER_GLADB_HEALTH                             = 160
MONSTER_GLADB_POWER_ARMOR_POWER                  = 55
MONSTER_GLADB_POWER_ARMOR_TYPE                   = "shield"
MONSTER_GLADB_DAMAGE_SCALE                       = 1.2
MONSTER_GLADB_DAMAGE_MELEE                       = 25
MONSTER_GLADB_DAMAGE_MAX_MELEE                   = 25
MONSTER_GLADB_ADDON_DAMAGE_MELEE                 = 0
MONSTER_GLADB_DAMAGE_TRACKER                     = 16

-- Gladc
MONSTER_GLADC_HEALTH                             = 190
MONSTER_GLADC_POWER_ARMOR_POWER                  = 95
MONSTER_GLADC_POWER_ARMOR_TYPE                   = "shield"
MONSTER_GLADC_DAMAGE_SCALE                       = 1
MONSTER_GLADC_DAMAGE_MELEE                       = 25
MONSTER_GLADC_DAMAGE_MAX_MELEE                   = 25
MONSTER_GLADC_ADDON_DAMAGE_MELEE                 = 0
MONSTER_GLADC_DAMAGE_PLASMA                      = 20

-- Tank
MONSTER_TANK_HEALTH                              = 630
MONSTER_TANK_ARMOR_POWER                         = 500
MONSTER_TANK_ARMOR_TYPE                          = "combat"
MONSTER_TANK_HEALTH_SCALE                        = 1
MONSTER_TANK_DAMAGE_SCALE                        = 1
MONSTER_TANK_DAMAGE_BLASTER2                     = 30
MONSTER_TANK_DAMAGE_HEAT                         = 50
MONSTER_TANK_DAMAGE_SLAM                         = 45

-- Tank Commander
MONSTER_TANK_COMMANDER_HEALTH                    = 1000
MONSTER_TANK_COMMANDER_ARMOR_POWER               = 650
MONSTER_TANK_COMMANDER_ARMOR_TYPE                = "combat"
MONSTER_TANK_COMMANDER_HEALTH_SCALE              = 1
MONSTER_TANK_COMMANDER_DAMAGE_SCALE              = 1.2
MONSTER_TANK_COMMANDER_DAMAGE_BLASTER            = 18
MONSTER_TANK_COMMANDER_DAMAGE_BLASTER2           = 30
MONSTER_TANK_COMMANDER_DAMAGE_FLECHETTE          = 10
MONSTER_TANK_COMMANDER_DAMAGE_GRENADE            = 50
MONSTER_TANK_COMMANDER_DAMAGE_HEAT               = 40
MONSTER_TANK_COMMANDER_DAMAGE_ROCKET             = 30
MONSTER_TANK_COMMANDER_DAMAGE_SLAM               = 45
MONSTER_TANK_COMMANDER_SPEED_GRENADE             = 1500

-- Tank 64
MONSTER_TANK_64_HEALTH                           = 1150
MONSTER_TANK_64_ARMOR_POWER                      = 750
MONSTER_TANK_64_ARMOR_TYPE                       = "combat"
MONSTER_TANK_64_HEALTH_SCALE                     = 1
MONSTER_TANK_64_DAMAGE_SCALE                     = 1
MONSTER_TANK_64_DAMAGE_BLASTER2                  = 26
MONSTER_TANK_64_DAMAGE_GRENADE                   = 50
MONSTER_TANK_64_DAMAGE_HEAT                      = 45
MONSTER_TANK_64_SPEED_GRENADE                    = 1500

-- Runnertank
MONSTER_RUNNERTANK_HEALTH                        = 850
MONSTER_RUNNERTANK_POWER_ARMOR_POWER             = 0
MONSTER_RUNNERTANK_DAMAGE_SCALE                  = 1
MONSTER_RUNNERTANK_DAMAGE_PLASMA                 = 18
MONSTER_RUNNERTANK_DAMAGE_RAILGUN                = 45
MONSTER_RUNNERTANK_DAMAGE_ROCKET                 = 35
MONSTER_RUNNERTANK_DAMAGE_SLAM                   = 45

-- Chick
MONSTER_CHICK_HEALTH                             = 145
MONSTER_CHICK_POWER_ARMOR_POWER                  = 45
MONSTER_CHICK_POWER_ARMOR_TYPE                   = "shield"
MONSTER_CHICK_DAMAGE_SCALE                       = 1
MONSTER_CHICK_DAMAGE_MELEE                       = 16
MONSTER_CHICK_DAMAGE_MAX_MELEE                   = 16
MONSTER_CHICK_ADDON_DAMAGE_MELEE                 = 0
MONSTER_CHICK_DAMAGE_ROCKET                      = 25

-- Chick Heat
MONSTER_CHICK_HEAT_HEALTH                        = 145
MONSTER_CHICK_HEAT_POWER_ARMOR_POWER             = 80
MONSTER_CHICK_HEAT_POWER_ARMOR_TYPE              = "shield"
MONSTER_CHICK_HEAT_HEALTH_SCALE                  = 1.5
MONSTER_CHICK_HEAT_DAMAGE_SCALE                  = 1.2
MONSTER_CHICK_HEAT_DAMAGE_HEAT                   = 40
MONSTER_CHICK_HEAT_DAMAGE_MELEE                  = 16
MONSTER_CHICK_HEAT_DAMAGE_MAX_MELEE              = 16
MONSTER_CHICK_HEAT_ADDON_DAMAGE_MELEE            = 0

-- Chickkl
MONSTER_CHICKKL_HEALTH                           = 300
MONSTER_CHICKKL_POWER_ARMOR_POWER                = 150
MONSTER_CHICKKL_POWER_ARMOR_TYPE                 = "shield"
MONSTER_CHICKKL_HEALTH_SCALE                     = 1.8
MONSTER_CHICKKL_DAMAGE_SCALE                     = 1.16
MONSTER_CHICKKL_DAMAGE_MELEE                     = 16
MONSTER_CHICKKL_DAMAGE_MAX_MELEE                 = 16
MONSTER_CHICKKL_ADDON_DAMAGE_MELEE               = 0
MONSTER_CHICKKL_DAMAGE_PLASMA                    = 15

-- Parasite
MONSTER_PARASITE_HEALTH                          = 115
MONSTER_PARASITE_POWER_ARMOR_POWER               = 0
MONSTER_PARASITE_DAMAGE_SCALE                    = 1

-- Brain
MONSTER_BRAIN_HEALTH                             = 135
MONSTER_BRAIN_POWER_ARMOR_POWER                  = 250
MONSTER_BRAIN_POWER_ARMOR_TYPE                   = "screen"
MONSTER_BRAIN_DAMAGE_SCALE                       = 1.1
MONSTER_BRAIN_DAMAGE_MAX_DABEAM                  = 5
MONSTER_BRAIN_ADDON_DAMAGE_DABEAM                = 0
MONSTER_BRAIN_DAMAGE_MELEE                       = 17

-- Mutant
MONSTER_MUTANT_HEALTH                            = 200
MONSTER_MUTANT_POWER_ARMOR_POWER                 = 0
MONSTER_MUTANT_DAMAGE_SCALE                      = 0.7

-- Redmutant
MONSTER_REDMUTANT_HEALTH                         = 520
MONSTER_REDMUTANT_POWER_ARMOR_POWER              = 0
MONSTER_REDMUTANT_HEALTH_SCALE                   = 1
MONSTER_REDMUTANT_DAMAGE_SCALE                   = 1

-- Berserk
MONSTER_BERSERK_HEALTH                           = 335
MONSTER_BERSERK_ARMOR_POWER                      = 120
MONSTER_BERSERK_ARMOR_TYPE                       = "combat"
MONSTER_BERSERK_DAMAGE_SCALE                     = 1.47
MONSTER_BERSERK_DAMAGE_MELEE                     = 21
MONSTER_BERSERK_DAMAGE_MAX_MELEE                 = 21
MONSTER_BERSERK_ADDON_DAMAGE_MELEE               = 0
MONSTER_BERSERK_DAMAGE_SLAM                      = 15

-- Berserkerkl
MONSTER_BERSERKERKL_HEALTH                       = 350
MONSTER_BERSERKERKL_POWER_ARMOR_POWER            = 100
MONSTER_BERSERKERKL_POWER_ARMOR_TYPE             = "shield"
MONSTER_BERSERKERKL_HEALTH_SCALE                 = 1
MONSTER_BERSERKERKL_DAMAGE_SCALE                 = 1.5
MONSTER_BERSERKERKL_DAMAGE_FIREBALL              = 45
MONSTER_BERSERKERKL_DAMAGE_MELEE                 = 21
MONSTER_BERSERKERKL_DAMAGE_MAX_MELEE             = 21
MONSTER_BERSERKERKL_ADDON_DAMAGE_MELEE           = 0
MONSTER_BERSERKERKL_DAMAGE_SLAM                  = 15

-- Flyer
MONSTER_FLYER_HEALTH                             = 60
MONSTER_FLYER_POWER_ARMOR_POWER                  = 0
MONSTER_FLYER_DAMAGE_SCALE                       = 0.3
MONSTER_FLYER_DAMAGE_BLASTER_BOLT                = 4
MONSTER_FLYER_DAMAGE_DABEAM                      = 3
MONSTER_FLYER_DAMAGE_ROCKET                      = 25

-- Hover
MONSTER_HOVER_HEALTH                             = 140
MONSTER_HOVER_ARMOR_POWER                        = 175
MONSTER_HOVER_ARMOR_TYPE                         = "combat"
MONSTER_HOVER_DAMAGE_SCALE                       = 1
MONSTER_HOVER_DAMAGE_GRENADE                     = 24
MONSTER_HOVER_DAMAGE_ROCKET                      = 15

-- Hover Vanilla
MONSTER_HOVER_VANILLA_HEALTH                     = 115
MONSTER_HOVER_VANILLA_ARMOR_POWER                = 210
MONSTER_HOVER_VANILLA_ARMOR_TYPE                 = "combat"
MONSTER_HOVER_VANILLA_DAMAGE_SCALE               = 1.2
MONSTER_HOVER_VANILLA_DAMAGE_BLASTER             = 1
MONSTER_HOVER_VANILLA_DAMAGE_MAX_BLASTER         = 1
MONSTER_HOVER_VANILLA_ADDON_DAMAGE_BLASTER       = 0
MONSTER_HOVER_VANILLA_DAMAGE_MAX_BLASTER2        = 1
MONSTER_HOVER_VANILLA_ADDON_DAMAGE_BLASTER2      = 0

-- Daedalus
MONSTER_DAEDALUS_HEALTH                          = 120
MONSTER_DAEDALUS_POWER_ARMOR_POWER               = 80
MONSTER_DAEDALUS_POWER_ARMOR_TYPE                = "shield"
MONSTER_DAEDALUS_DAMAGE_SCALE                    = 0.8
MONSTER_DAEDALUS_DAMAGE_BLASTER2                 = 1
MONSTER_DAEDALUS_DAMAGE_MAX_BLASTER2             = 1
MONSTER_DAEDALUS_ADDON_DAMAGE_BLASTER2           = 0

-- Daedalus Bomber
MONSTER_DAEDALUS_BOMBER_HEALTH                   = 150
MONSTER_DAEDALUS_BOMBER_POWER_ARMOR_POWER        = 100
MONSTER_DAEDALUS_BOMBER_POWER_ARMOR_TYPE         = "screen"
MONSTER_DAEDALUS_BOMBER_DAMAGE_SCALE             = 1.2
MONSTER_DAEDALUS_BOMBER_DAMAGE_MAX_BLASTER       = 1
MONSTER_DAEDALUS_BOMBER_ADDON_DAMAGE_BLASTER     = 0
MONSTER_DAEDALUS_BOMBER_DAMAGE_MAX_BLASTER2      = 1
MONSTER_DAEDALUS_BOMBER_ADDON_DAMAGE_BLASTER2    = 0
MONSTER_DAEDALUS_BOMBER_DAMAGE_GRENADE           = 18

-- Floater
MONSTER_FLOATER_HEALTH                           = 120
MONSTER_FLOATER_ARMOR_POWER                      = 180
MONSTER_FLOATER_ARMOR_TYPE                       = "combat"
MONSTER_FLOATER_DAMAGE_SCALE                     = 0.4
MONSTER_FLOATER_DAMAGE_BLASTER                   = 1
MONSTER_FLOATER_DAMAGE_MAX_BLASTER               = 1
MONSTER_FLOATER_ADDON_DAMAGE_BLASTER             = 0
MONSTER_FLOATER_DAMAGE_MELEE                     = 8

-- Floater Tracker
MONSTER_FLOATER_TRACKER_HEALTH                   = 200
MONSTER_FLOATER_TRACKER_POWER_ARMOR_POWER        = 120
MONSTER_FLOATER_TRACKER_POWER_ARMOR_TYPE         = "screen"
MONSTER_FLOATER_TRACKER_DAMAGE_SCALE             = 0.5
MONSTER_FLOATER_TRACKER_DAMAGE_TRACKER           = 8

-- Fixbot
MONSTER_FIXBOT_HEALTH                            = 110
MONSTER_FIXBOT_POWER_ARMOR_POWER                 = 25
MONSTER_FIXBOT_POWER_ARMOR_TYPE                  = "shield"
MONSTER_FIXBOT_DAMAGE_SCALE                      = 1
MONSTER_FIXBOT_DAMAGE_BLASTER_BOLT               = 8
MONSTER_FIXBOT_DAMAGE_IONRIPPER                  = 20
MONSTER_FIXBOT_DAMAGE_MAX_IONRIPPER              = 20
MONSTER_FIXBOT_ADDON_DAMAGE_IONRIPPER            = 0
MONSTER_FIXBOT_DAMAGE_PLASMA                     = 20
MONSTER_FIXBOT_DAMAGE_MAX_PLASMA                 = 20
MONSTER_FIXBOT_ADDON_DAMAGE_PLASMA               = 0

-- Fixbotkl
MONSTER_FIXBOTKL_HEALTH                          = 300
MONSTER_FIXBOTKL_POWER_ARMOR_POWER               = 500
MONSTER_FIXBOTKL_POWER_ARMOR_TYPE                = "shield"
MONSTER_FIXBOTKL_HEALTH_SCALE                    = 1
MONSTER_FIXBOTKL_DAMAGE_SCALE                    = 1.2
MONSTER_FIXBOTKL_DAMAGE_BLASTER_BOLT             = 10
MONSTER_FIXBOTKL_DAMAGE_IONRIPPER                = 15
MONSTER_FIXBOTKL_DAMAGE_PLASMA                   = 19

-- Gekk
MONSTER_GEKK_HEALTH                              = 110
MONSTER_GEKK_POWER_ARMOR_POWER                   = 0
MONSTER_GEKK_DAMAGE_SCALE                        = 1.1
MONSTER_GEKK_DAMAGE_MELEE                        = 10
MONSTER_GEKK_DAMAGE_MAX_MELEE                    = 10
MONSTER_GEKK_ADDON_DAMAGE_MELEE                  = 0
MONSTER_GEKK_DAMAGE_PLASMA                       = 7

-- Gekkkl
MONSTER_GEKKKL_HEALTH                            = 400
MONSTER_GEKKKL_POWER_ARMOR_POWER                 = 150
MONSTER_GEKKKL_POWER_ARMOR_TYPE                  = "screen"
MONSTER_GEKKKL_HEALTH_SCALE                      = 1
MONSTER_GEKKKL_DAMAGE_SCALE                      = 1.2
MONSTER_GEKKKL_DAMAGE_MELEE                      = 10
MONSTER_GEKKKL_DAMAGE_MAX_MELEE                  = 10
MONSTER_GEKKKL_ADDON_DAMAGE_MELEE                = 0
MONSTER_GEKKKL_DAMAGE_PLASMA                     = 7
MONSTER_GEKKKL_DAMAGE_MAX_PLASMA                 = 7
MONSTER_GEKKKL_ADDON_DAMAGE_PLASMA               = 0
MONSTER_GEKKKL_DAMAGE_SLAM                       = 45

-- Stalker
MONSTER_STALKER_HEALTH                           = 150
MONSTER_STALKER_POWER_ARMOR_POWER                = 0
MONSTER_STALKER_DAMAGE_SCALE                     = 1

-- Flipper
MONSTER_FLIPPER_HEALTH                           = 60
MONSTER_FLIPPER_POWER_ARMOR_POWER                = 0
MONSTER_FLIPPER_DAMAGE_SCALE                     = 1

-- Carrier
MONSTER_CARRIER_HEALTH                           = 2750
MONSTER_CARRIER_POWER_ARMOR_POWER                = 450
MONSTER_CARRIER_POWER_ARMOR_TYPE                 = "shield"
MONSTER_CARRIER_HEALTH_SCALE                     = 1
MONSTER_CARRIER_DAMAGE_SCALE                     = 1
MONSTER_CARRIER_DAMAGE_GRENADE                   = 45
MONSTER_CARRIER_DAMAGE_MACHINEGUN                = 5

-- Carrier Mini
MONSTER_CARRIER_MINI_HEALTH                      = 500
MONSTER_CARRIER_MINI_POWER_ARMOR_POWER           = 150
MONSTER_CARRIER_MINI_POWER_ARMOR_TYPE            = "shield"
MONSTER_CARRIER_MINI_HEALTH_SCALE                = 1
MONSTER_CARRIER_MINI_DAMAGE_SCALE                = 0.9
MONSTER_CARRIER_MINI_DAMAGE_GRENADE              = 30
MONSTER_CARRIER_MINI_DAMAGE_HEAT                 = 25
MONSTER_CARRIER_MINI_DAMAGE_MACHINEGUN           = 5
MONSTER_CARRIER_MINI_DAMAGE_RAILGUN              = 45
MONSTER_CARRIER_MINI_DAMAGE_ROCKET               = 25

-- Widow
MONSTER_WIDOW_HEALTH                             = 1200
MONSTER_WIDOW_POWER_ARMOR_POWER                  = 400
MONSTER_WIDOW_POWER_ARMOR_TYPE                   = "shield"
MONSTER_WIDOW_HEALTH_SCALE                       = 1
MONSTER_WIDOW_DAMAGE_SCALE                       = 1

-- Widow1
MONSTER_WIDOW1_HEALTH                            = 900
MONSTER_WIDOW1_POWER_ARMOR_POWER                 = 380
MONSTER_WIDOW1_POWER_ARMOR_TYPE                  = "shield"
MONSTER_WIDOW1_HEALTH_SCALE                      = 0.8
MONSTER_WIDOW1_DAMAGE_SCALE                      = 1

-- Widow2
MONSTER_WIDOW2_HEALTH                            = 1500
MONSTER_WIDOW2_POWER_ARMOR_POWER                 = 600
MONSTER_WIDOW2_POWER_ARMOR_TYPE                  = "shield"
MONSTER_WIDOW2_HEALTH_SCALE                      = 1
MONSTER_WIDOW2_DAMAGE_SCALE                      = 1.3
MONSTER_WIDOW2_DAMAGE_TRACKER                    = 20

-- Spider
MONSTER_SPIDER_HEALTH                            = 550
MONSTER_SPIDER_POWER_ARMOR_POWER                 = 0
MONSTER_SPIDER_HEALTH_SCALE                      = 1
MONSTER_SPIDER_DAMAGE_SCALE                      = 1

-- Arachnid
MONSTER_ARACHNID_HEALTH                          = 320
MONSTER_ARACHNID_POWER_ARMOR_POWER               = 200
MONSTER_ARACHNID_POWER_ARMOR_TYPE                = "shield"
MONSTER_ARACHNID_HEALTH_SCALE                    = 1
MONSTER_ARACHNID_DAMAGE_SCALE                    = 1
MONSTER_ARACHNID_DAMAGE_RAILGUN                  = 42

-- Arachnid2
MONSTER_ARACHNID2_HEALTH                         = 350
MONSTER_ARACHNID2_POWER_ARMOR_POWER              = 220
MONSTER_ARACHNID2_POWER_ARMOR_TYPE               = "shield"
MONSTER_ARACHNID2_HEALTH_SCALE                   = 1
MONSTER_ARACHNID2_DAMAGE_SCALE                   = 1.2
MONSTER_ARACHNID2_DAMAGE_HEAT                    = 50

-- Gm Arachnid
MONSTER_GM_ARACHNID_HEALTH                       = 680
MONSTER_GM_ARACHNID_POWER_ARMOR_POWER            = 220
MONSTER_GM_ARACHNID_POWER_ARMOR_TYPE             = "shield"
MONSTER_GM_ARACHNID_HEALTH_SCALE                 = 1.1
MONSTER_GM_ARACHNID_DAMAGE_SCALE                 = 1.2
MONSTER_GM_ARACHNID_DAMAGE_HEAT                  = 25
MONSTER_GM_ARACHNID_DAMAGE_ROCKET                = 30

-- Psxarachnid
MONSTER_PSXARACHNID_HEALTH                       = 600
MONSTER_PSXARACHNID_POWER_ARMOR_POWER            = 500
MONSTER_PSXARACHNID_POWER_ARMOR_TYPE             = "combat"
MONSTER_PSXARACHNID_HEALTH_SCALE                 = 1.5
MONSTER_PSXARACHNID_DAMAGE_SCALE                 = 1.2
MONSTER_PSXARACHNID_DAMAGE_RAILGUN               = 30

-- Shambler
MONSTER_SHAMBLER_HEALTH                          = 950
MONSTER_SHAMBLER_POWER_ARMOR_POWER               = 0
MONSTER_SHAMBLER_HEALTH_SCALE                    = 1
MONSTER_SHAMBLER_DAMAGE_SCALE                    = 1
MONSTER_SHAMBLER_DAMAGE_FIREBALL                 = 30
MONSTER_SHAMBLER_DAMAGE_MELEE                    = 115

-- Shambler Small
MONSTER_SHAMBLER_SMALL_HEALTH                    = 350
MONSTER_SHAMBLER_SMALL_POWER_ARMOR_POWER         = 0
MONSTER_SHAMBLER_SMALL_HEALTH_SCALE              = 0.5
MONSTER_SHAMBLER_SMALL_DAMAGE_SCALE              = 1
MONSTER_SHAMBLER_SMALL_DAMAGE_MELEE              = 45

-- Shamblerkl
MONSTER_SHAMBLERKL_HEALTH                        = 2500
MONSTER_SHAMBLERKL_POWER_ARMOR_POWER             = 0
MONSTER_SHAMBLERKL_HEALTH_SCALE                  = 1.4
MONSTER_SHAMBLERKL_DAMAGE_SCALE                  = 1.2
MONSTER_SHAMBLERKL_DAMAGE_FIREBALL               = 24
MONSTER_SHAMBLERKL_DAMAGE_MAX_FIREBALL           = 30
MONSTER_SHAMBLERKL_ADDON_DAMAGE_FIREBALL         = 0
MONSTER_SHAMBLERKL_DAMAGE_MELEE                  = 115

-- Boss2
MONSTER_BOSS2_HEALTH                             = 750
MONSTER_BOSS2_POWER_ARMOR_POWER                  = 450
MONSTER_BOSS2_POWER_ARMOR_TYPE                   = "shield"
MONSTER_BOSS2_HEALTH_SCALE                       = 1
MONSTER_BOSS2_DAMAGE_SCALE                       = 0.5
MONSTER_BOSS2_DAMAGE_BLASTER                     = 2
MONSTER_BOSS2_DAMAGE_MAX_BLASTER                 = 2
MONSTER_BOSS2_ADDON_DAMAGE_BLASTER               = 0
MONSTER_BOSS2_DAMAGE_BLASTER_BOLT                = 8

-- Boss2 64
MONSTER_BOSS2_64_HEALTH                          = 800
MONSTER_BOSS2_64_POWER_ARMOR_POWER               = 100
MONSTER_BOSS2_64_POWER_ARMOR_TYPE                = "screen"
MONSTER_BOSS2_64_HEALTH_SCALE                    = 1
MONSTER_BOSS2_64_DAMAGE_SCALE                    = 0.5
MONSTER_BOSS2_64_DAMAGE_BLASTER                  = 2
MONSTER_BOSS2_64_DAMAGE_MAX_BLASTER              = 2
MONSTER_BOSS2_64_ADDON_DAMAGE_BLASTER            = 0
MONSTER_BOSS2_64_DAMAGE_BLASTER_BOLT             = 8

-- Boss2 Mini
MONSTER_BOSS2_MINI_HEALTH                        = 700
MONSTER_BOSS2_MINI_POWER_ARMOR_POWER             = 100
MONSTER_BOSS2_MINI_POWER_ARMOR_TYPE              = "shield"
MONSTER_BOSS2_MINI_HEALTH_SCALE                  = 0.7
MONSTER_BOSS2_MINI_DAMAGE_SCALE                  = 0.5
MONSTER_BOSS2_MINI_DAMAGE_BLASTER                = 2
MONSTER_BOSS2_MINI_DAMAGE_MAX_BLASTER            = 2
MONSTER_BOSS2_MINI_ADDON_DAMAGE_BLASTER          = 0
MONSTER_BOSS2_MINI_DAMAGE_BLASTER_BOLT           = 8
MONSTER_BOSS2_MINI_DAMAGE_ROCKET                 = 45

-- Boss2kl
MONSTER_BOSS2KL_HEALTH                           = 2000
MONSTER_BOSS2KL_POWER_ARMOR_POWER                = 500
MONSTER_BOSS2KL_POWER_ARMOR_TYPE                 = "shield"
MONSTER_BOSS2KL_HEALTH_SCALE                     = 1
MONSTER_BOSS2KL_DAMAGE_SCALE                     = 0.6

-- Supertank
MONSTER_SUPERTANK_HEALTH                         = 2500
MONSTER_SUPERTANK_POWER_ARMOR_POWER              = 1000
MONSTER_SUPERTANK_POWER_ARMOR_TYPE               = "screen"
MONSTER_SUPERTANK_HEALTH_SCALE                   = 1
MONSTER_SUPERTANK_DAMAGE_SCALE                   = 1
MONSTER_SUPERTANK_DAMAGE_HEAT                    = 40

-- Supertankkl
MONSTER_SUPERTANKKL_HEALTH                       = 3000
MONSTER_SUPERTANKKL_POWER_ARMOR_POWER            = 1500
MONSTER_SUPERTANKKL_POWER_ARMOR_TYPE             = "screen"
MONSTER_SUPERTANKKL_HEALTH_SCALE                 = 1.5
MONSTER_SUPERTANKKL_DAMAGE_SCALE                 = 1.2

-- Makron
MONSTER_MAKRON_HEALTH                            = 800
MONSTER_MAKRON_POWER_ARMOR_POWER                 = 250
MONSTER_MAKRON_POWER_ARMOR_TYPE                  = "combat"
MONSTER_MAKRON_HEALTH_SCALE                      = 1
MONSTER_MAKRON_DAMAGE_SCALE                      = 1.1

-- Makronkl
MONSTER_MAKRONKL_HEALTH                          = 3000
MONSTER_MAKRONKL_POWER_ARMOR_POWER               = 600
MONSTER_MAKRONKL_POWER_ARMOR_TYPE                = "shield"
MONSTER_MAKRONKL_HEALTH_SCALE                    = 1.5
MONSTER_MAKRONKL_DAMAGE_SCALE                    = 1.2
MONSTER_MAKRONKL_DAMAGE_BFG                      = 50
MONSTER_MAKRONKL_DAMAGE_MAX_BFG                  = 50
MONSTER_MAKRONKL_ADDON_DAMAGE_BFG                = 0
MONSTER_MAKRONKL_DAMAGE_BLASTER                  = 15
MONSTER_MAKRONKL_DAMAGE_MAX_BLASTER              = 15
MONSTER_MAKRONKL_ADDON_DAMAGE_BLASTER            = 0
MONSTER_MAKRONKL_DAMAGE_RAILGUN                  = 50
MONSTER_MAKRONKL_DAMAGE_MAX_RAILGUN              = 50
MONSTER_MAKRONKL_ADDON_DAMAGE_RAILGUN            = 0

-- Jorg
MONSTER_JORG_HEALTH                              = 2500
MONSTER_JORG_POWER_ARMOR_POWER                   = 0
MONSTER_JORG_DAMAGE_SCALE                        = 1

-- Jorg Small
MONSTER_JORG_SMALL_HEALTH                        = 350
MONSTER_JORG_SMALL_ARMOR_POWER                   = 50
MONSTER_JORG_SMALL_ARMOR_TYPE                    = "combat"
MONSTER_JORG_SMALL_HEALTH_SCALE                  = 0.3
MONSTER_JORG_SMALL_DAMAGE_SCALE                  = 1
MONSTER_JORG_SMALL_DAMAGE_TRACKER                = 13

-- Boss5
MONSTER_BOSS5_HEALTH                             = 4200
MONSTER_BOSS5_POWER_ARMOR_POWER                  = 2250
MONSTER_BOSS5_POWER_ARMOR_TYPE                   = "shield"
MONSTER_BOSS5_HEALTH_SCALE                       = 1
MONSTER_BOSS5_DAMAGE_SCALE                       = 0.8
MONSTER_BOSS5_DAMAGE_HEAT                        = 40

-- Guardian
MONSTER_GUARDIAN_HEALTH                          = 4000
MONSTER_GUARDIAN_POWER_ARMOR_POWER               = 500
MONSTER_GUARDIAN_POWER_ARMOR_TYPE                = "shield"
MONSTER_GUARDIAN_HEALTH_SCALE                    = 1
MONSTER_GUARDIAN_DAMAGE_SCALE                    = 1.8
MONSTER_GUARDIAN_DAMAGE_BLASTER                  = 3
MONSTER_GUARDIAN_DAMAGE_MAX_BLASTER              = 3
MONSTER_GUARDIAN_ADDON_DAMAGE_BLASTER            = 0
MONSTER_GUARDIAN_DAMAGE_DABEAM                   = 15
MONSTER_GUARDIAN_DAMAGE_MAX_DABEAM               = 15
MONSTER_GUARDIAN_ADDON_DAMAGE_DABEAM             = 0
MONSTER_GUARDIAN_DAMAGE_MAX_GRENADE              = 40
MONSTER_GUARDIAN_ADDON_DAMAGE_GRENADE            = 0
MONSTER_GUARDIAN_DAMAGE_IONRIPPER                = 25
MONSTER_GUARDIAN_DAMAGE_MAX_ROCKET               = 40
MONSTER_GUARDIAN_ADDON_DAMAGE_ROCKET             = 0

-- Psxguardian
MONSTER_PSXGUARDIAN_HEALTH                       = 3500
MONSTER_PSXGUARDIAN_POWER_ARMOR_POWER            = 4000
MONSTER_PSXGUARDIAN_POWER_ARMOR_TYPE             = "shield"
MONSTER_PSXGUARDIAN_HEALTH_SCALE                 = 0.8
MONSTER_PSXGUARDIAN_DAMAGE_SCALE                 = 0.9
MONSTER_PSXGUARDIAN_DAMAGE_BLASTER               = 3
MONSTER_PSXGUARDIAN_DAMAGE_MAX_BLASTER           = 3
MONSTER_PSXGUARDIAN_ADDON_DAMAGE_BLASTER         = 0
MONSTER_PSXGUARDIAN_DAMAGE_DABEAM                = 15
MONSTER_PSXGUARDIAN_DAMAGE_HEAT                  = 20
MONSTER_PSXGUARDIAN_DAMAGE_MELEE                 = 85

-- Janitor
MONSTER_JANITOR_HEALTH                           = 1075
MONSTER_JANITOR_POWER_ARMOR_POWER                = 500
MONSTER_JANITOR_POWER_ARMOR_TYPE                 = "screen"
MONSTER_JANITOR_HEALTH_SCALE                     = 1
MONSTER_JANITOR_DAMAGE_SCALE                     = 1.2
MONSTER_JANITOR_DAMAGE_ROCKET                    = 25

-- Janitor2
MONSTER_JANITOR2_HEALTH                          = 880
MONSTER_JANITOR2_POWER_ARMOR_POWER               = 385
MONSTER_JANITOR2_POWER_ARMOR_TYPE                = "shield"
MONSTER_JANITOR2_HEALTH_SCALE                    = 1
MONSTER_JANITOR2_DAMAGE_SCALE                    = 1.1
MONSTER_JANITOR2_DAMAGE_MAX_BLASTER              = 3
MONSTER_JANITOR2_ADDON_DAMAGE_BLASTER            = 0
MONSTER_JANITOR2_DAMAGE_GRENADE                  = 40
MONSTER_JANITOR2_DAMAGE_IONRIPPER                = 25
MONSTER_JANITOR2_DAMAGE_ROCKET                   = 30
MONSTER_JANITOR2_SPEED_GRENADE                   = 1300

-- Tank Spawner
MONSTER_TANK_SPAWNER_HEALTH                      = 475
MONSTER_TANK_SPAWNER_ARMOR_POWER                 = 305
MONSTER_TANK_SPAWNER_ARMOR_TYPE                  = "screen"
MONSTER_TANK_SPAWNER_DAMAGE_SCALE                = 1.1
MONSTER_TANK_SPAWNER_DAMAGE_BLASTER              = 20
MONSTER_TANK_SPAWNER_DAMAGE_BLASTER2             = 30
MONSTER_TANK_SPAWNER_DAMAGE_MAX_BLASTER2         = 30
MONSTER_TANK_SPAWNER_ADDON_DAMAGE_BLASTER2       = 0
MONSTER_TANK_SPAWNER_DAMAGE_BOLT                 = 40
MONSTER_TANK_SPAWNER_DAMAGE_MACHINEGUN           = 8
MONSTER_TANK_SPAWNER_DAMAGE_ROCKET               = 50
MONSTER_TANK_SPAWNER_DAMAGE_MAX_ROCKET           = 50
MONSTER_TANK_SPAWNER_ADDON_DAMAGE_ROCKET         = 0
MONSTER_TANK_SPAWNER_DAMAGE_SLAM                 = 45

-- Perrokl
MONSTER_PERROKL_HEALTH                           = 800
MONSTER_PERROKL_POWER_ARMOR_POWER                = 0
MONSTER_PERROKL_HEALTH_SCALE                     = 1
MONSTER_PERROKL_DAMAGE_SCALE                     = 1.2
MONSTER_PERROKL_DAMAGE_PROBOSCIS                 = 5
MONSTER_PERROKL_DAMAGE_MAX_PROBOSCIS             = 5
MONSTER_PERROKL_ADDON_DAMAGE_PROBOSCIS           = 0

-- Kamikaze
MONSTER_KAMIKAZE_HEALTH                          = 50
MONSTER_KAMIKAZE_DAMAGE_SCALE                    = 1

-- Monster Level Scaling

-- Arachnid Level Scaling
MONSTER_LEVEL_ARACHNID_INITIAL_HEALTH            = 320
MONSTER_LEVEL_ARACHNID_ADDON_HEALTH              = 45
MONSTER_LEVEL_ARACHNID_INITIAL_POWER_ARMOR       = 200
MONSTER_LEVEL_ARACHNID_ADDON_POWER_ARMOR         = 25

-- Arachnid2 Level Scaling
MONSTER_LEVEL_ARACHNID2_INITIAL_HEALTH           = 350
MONSTER_LEVEL_ARACHNID2_ADDON_HEALTH             = 55
MONSTER_LEVEL_ARACHNID2_INITIAL_POWER_ARMOR      = 220
MONSTER_LEVEL_ARACHNID2_ADDON_POWER_ARMOR        = 30

-- Berserk Level Scaling
MONSTER_LEVEL_BERSERK_INITIAL_HEALTH             = 335
MONSTER_LEVEL_BERSERK_ADDON_HEALTH               = 70
MONSTER_LEVEL_BERSERK_INITIAL_ARMOR              = 120
MONSTER_LEVEL_BERSERK_ADDON_ARMOR                = 30

-- Berserkerkl Level Scaling
MONSTER_LEVEL_BERSERKERKL_INITIAL_HEALTH         = 350
MONSTER_LEVEL_BERSERKERKL_ADDON_HEALTH           = 75
MONSTER_LEVEL_BERSERKERKL_INITIAL_POWER_ARMOR    = 100
MONSTER_LEVEL_BERSERKERKL_ADDON_POWER_ARMOR      = 35

-- Boss2 64 Level Scaling
MONSTER_LEVEL_BOSS2_64_INITIAL_HEALTH            = 800
MONSTER_LEVEL_BOSS2_64_ADDON_HEALTH              = 100
MONSTER_LEVEL_BOSS2_64_INITIAL_POWER_ARMOR       = 100
MONSTER_LEVEL_BOSS2_64_ADDON_POWER_ARMOR         = 30

-- Boss2 Mini Level Scaling
MONSTER_LEVEL_BOSS2_MINI_INITIAL_HEALTH          = 700
MONSTER_LEVEL_BOSS2_MINI_ADDON_HEALTH            = 90
MONSTER_LEVEL_BOSS2_MINI_INITIAL_POWER_ARMOR     = 100
MONSTER_LEVEL_BOSS2_MINI_ADDON_POWER_ARMOR       = 30

-- Boss5 Level Scaling
MONSTER_LEVEL_BOSS5_INITIAL_HEALTH               = 4200
MONSTER_LEVEL_BOSS5_ADDON_HEALTH                 = 200
MONSTER_LEVEL_BOSS5_INITIAL_POWER_ARMOR          = 2250
MONSTER_LEVEL_BOSS5_ADDON_POWER_ARMOR            = 100

-- Brain Level Scaling
MONSTER_LEVEL_BRAIN_INITIAL_HEALTH               = 135
MONSTER_LEVEL_BRAIN_ADDON_HEALTH                 = 40
MONSTER_LEVEL_BRAIN_INITIAL_ARMOR                = 0
MONSTER_LEVEL_BRAIN_ADDON_ARMOR                  = 150
MONSTER_LEVEL_BRAIN_INITIAL_POWER_ARMOR          = 250
MONSTER_LEVEL_BRAIN_ADDON_POWER_ARMOR            = 50

-- Carrier Mini Level Scaling
MONSTER_LEVEL_CARRIER_MINI_INITIAL_HEALTH        = 500
MONSTER_LEVEL_CARRIER_MINI_ADDON_HEALTH          = 70
MONSTER_LEVEL_CARRIER_MINI_INITIAL_POWER_ARMOR   = 150
MONSTER_LEVEL_CARRIER_MINI_ADDON_POWER_ARMOR     = 40

-- Chick Level Scaling
MONSTER_LEVEL_CHICK_INITIAL_HEALTH               = 145
MONSTER_LEVEL_CHICK_ADDON_HEALTH                 = 15
MONSTER_LEVEL_CHICK_INITIAL_POWER_ARMOR          = 25
MONSTER_LEVEL_CHICK_ADDON_POWER_ARMOR            = 15

-- Chick Heat Level Scaling
MONSTER_LEVEL_CHICK_HEAT_INITIAL_HEALTH          = 60
MONSTER_LEVEL_CHICK_HEAT_ADDON_HEALTH            = 15
MONSTER_LEVEL_CHICK_HEAT_INITIAL_POWER_ARMOR     = 35
MONSTER_LEVEL_CHICK_HEAT_ADDON_POWER_ARMOR       = 20

-- Chickkl Level Scaling
MONSTER_LEVEL_CHICKKL_INITIAL_HEALTH             = 300
MONSTER_LEVEL_CHICKKL_ADDON_HEALTH               = 50
MONSTER_LEVEL_CHICKKL_INITIAL_POWER_ARMOR        = 150
MONSTER_LEVEL_CHICKKL_ADDON_POWER_ARMOR          = 40

-- Daedalus Level Scaling
MONSTER_LEVEL_DAEDALUS_INITIAL_HEALTH            = 120
MONSTER_LEVEL_DAEDALUS_ADDON_HEALTH              = 25
MONSTER_LEVEL_DAEDALUS_INITIAL_POWER_ARMOR       = 80
MONSTER_LEVEL_DAEDALUS_ADDON_POWER_ARMOR         = 20

-- Daedalus Bomber Level Scaling
MONSTER_LEVEL_DAEDALUS_BOMBER_INITIAL_HEALTH     = 150
MONSTER_LEVEL_DAEDALUS_BOMBER_ADDON_HEALTH       = 30
MONSTER_LEVEL_DAEDALUS_BOMBER_INITIAL_POWER_ARMOR = 100
MONSTER_LEVEL_DAEDALUS_BOMBER_ADDON_POWER_ARMOR  = 25

-- Fixbot Level Scaling
MONSTER_LEVEL_FIXBOT_INITIAL_HEALTH              = 110
MONSTER_LEVEL_FIXBOT_ADDON_HEALTH                = 25
MONSTER_LEVEL_FIXBOT_INITIAL_POWER_ARMOR         = 25
MONSTER_LEVEL_FIXBOT_ADDON_POWER_ARMOR           = 10

-- Fixbotkl Level Scaling
MONSTER_LEVEL_FIXBOTKL_INITIAL_HEALTH            = 1000
MONSTER_LEVEL_FIXBOTKL_ADDON_HEALTH              = 150
MONSTER_LEVEL_FIXBOTKL_INITIAL_POWER_ARMOR       = 800
MONSTER_LEVEL_FIXBOTKL_ADDON_POWER_ARMOR         = 150

-- Flipper Level Scaling
MONSTER_LEVEL_FLIPPER_INITIAL_HEALTH             = 60
MONSTER_LEVEL_FLIPPER_ADDON_HEALTH               = 15
MONSTER_LEVEL_FLIPPER_INITIAL_ARMOR              = 0
MONSTER_LEVEL_FLIPPER_ADDON_ARMOR                = 0

-- Floater Level Scaling
MONSTER_LEVEL_FLOATER_INITIAL_HEALTH             = 120
MONSTER_LEVEL_FLOATER_ADDON_HEALTH               = 20
MONSTER_LEVEL_FLOATER_INITIAL_ARMOR              = 150
MONSTER_LEVEL_FLOATER_ADDON_ARMOR                = 60

-- Floater Tracker Level Scaling
MONSTER_LEVEL_FLOATER_TRACKER_INITIAL_HEALTH     = 200
MONSTER_LEVEL_FLOATER_TRACKER_ADDON_HEALTH       = 40
MONSTER_LEVEL_FLOATER_TRACKER_INITIAL_POWER_ARMOR = 120
MONSTER_LEVEL_FLOATER_TRACKER_ADDON_POWER_ARMOR  = 20

-- Flyer Level Scaling
MONSTER_LEVEL_FLYER_INITIAL_HEALTH               = 60
MONSTER_LEVEL_FLYER_ADDON_HEALTH                 = 20
MONSTER_LEVEL_FLYER_INITIAL_ARMOR                = 50
MONSTER_LEVEL_FLYER_ADDON_ARMOR                  = 20

-- Gekk Level Scaling
MONSTER_LEVEL_GEKK_INITIAL_HEALTH                = 110
MONSTER_LEVEL_GEKK_ADDON_HEALTH                  = 25
MONSTER_LEVEL_GEKK_INITIAL_ARMOR                 = 0
MONSTER_LEVEL_GEKK_ADDON_ARMOR                   = 0

-- Gekkkl Level Scaling
MONSTER_LEVEL_GEKKKL_INITIAL_HEALTH              = 400
MONSTER_LEVEL_GEKKKL_ADDON_HEALTH                = 60
MONSTER_LEVEL_GEKKKL_INITIAL_POWER_ARMOR         = 150
MONSTER_LEVEL_GEKKKL_ADDON_POWER_ARMOR           = 40

-- Gladb Level Scaling
MONSTER_LEVEL_GLADB_INITIAL_HEALTH               = 160
MONSTER_LEVEL_GLADB_ADDON_HEALTH                 = 30
MONSTER_LEVEL_GLADB_INITIAL_ARMOR                = 55
MONSTER_LEVEL_GLADB_ADDON_ARMOR                  = 20

-- Gladc Level Scaling
MONSTER_LEVEL_GLADC_INITIAL_HEALTH               = 190
MONSTER_LEVEL_GLADC_ADDON_HEALTH                 = 35
MONSTER_LEVEL_GLADC_INITIAL_ARMOR                = 95
MONSTER_LEVEL_GLADC_ADDON_ARMOR                  = 25

-- Gladiator Level Scaling
MONSTER_LEVEL_GLADIATOR_INITIAL_HEALTH           = 110
MONSTER_LEVEL_GLADIATOR_ADDON_HEALTH             = 25
MONSTER_LEVEL_GLADIATOR_INITIAL_ARMOR            = 120
MONSTER_LEVEL_GLADIATOR_ADDON_ARMOR              = 20

-- Gm Arachnid Level Scaling
MONSTER_LEVEL_GM_ARACHNID_INITIAL_HEALTH         = 680
MONSTER_LEVEL_GM_ARACHNID_ADDON_HEALTH           = 50
MONSTER_LEVEL_GM_ARACHNID_INITIAL_POWER_ARMOR    = 220
MONSTER_LEVEL_GM_ARACHNID_ADDON_POWER_ARMOR      = 40

-- Guncmdr Level Scaling
MONSTER_LEVEL_GUNCMDR_INITIAL_HEALTH             = 325
MONSTER_LEVEL_GUNCMDR_ADDON_HEALTH               = 40
MONSTER_LEVEL_GUNCMDR_INITIAL_ARMOR              = 120
MONSTER_LEVEL_GUNCMDR_ADDON_ARMOR                = 30

-- Guncmdr Vanilla Level Scaling
MONSTER_LEVEL_GUNCMDR_VANILLA_INITIAL_HEALTH     = 200
MONSTER_LEVEL_GUNCMDR_VANILLA_ADDON_HEALTH       = 35
MONSTER_LEVEL_GUNCMDR_VANILLA_INITIAL_ARMOR      = 80
MONSTER_LEVEL_GUNCMDR_VANILLA_ADDON_ARMOR        = 25

-- Guncmdrkl Level Scaling
MONSTER_LEVEL_GUNCMDRKL_INITIAL_HEALTH           = 500
MONSTER_LEVEL_GUNCMDRKL_ADDON_HEALTH             = 70
MONSTER_LEVEL_GUNCMDRKL_INITIAL_ARMOR            = 180
MONSTER_LEVEL_GUNCMDRKL_ADDON_ARMOR              = 40

-- Gunner Level Scaling
MONSTER_LEVEL_GUNNER_INITIAL_HEALTH              = 175
MONSTER_LEVEL_GUNNER_ADDON_HEALTH                = 25
MONSTER_LEVEL_GUNNER_INITIAL_POWER_ARMOR         = 65
MONSTER_LEVEL_GUNNER_ADDON_POWER_ARMOR           = 35

-- Gunner Vanilla Level Scaling
MONSTER_LEVEL_GUNNER_VANILLA_INITIAL_HEALTH      = 175
MONSTER_LEVEL_GUNNER_VANILLA_ADDON_HEALTH        = 20
MONSTER_LEVEL_GUNNER_VANILLA_INITIAL_ARMOR       = 85
MONSTER_LEVEL_GUNNER_VANILLA_ADDON_ARMOR         = 20

-- Hover Level Scaling
MONSTER_LEVEL_HOVER_INITIAL_HEALTH               = 140
MONSTER_LEVEL_HOVER_ADDON_HEALTH                 = 15
MONSTER_LEVEL_HOVER_INITIAL_ARMOR                = 150
MONSTER_LEVEL_HOVER_ADDON_ARMOR                  = 20

-- Hover Vanilla Level Scaling
MONSTER_LEVEL_HOVER_VANILLA_INITIAL_HEALTH       = 115
MONSTER_LEVEL_HOVER_VANILLA_ADDON_HEALTH         = 15
MONSTER_LEVEL_HOVER_VANILLA_INITIAL_ARMOR        = 210
MONSTER_LEVEL_HOVER_VANILLA_ADDON_ARMOR          = 50

-- Infantry Level Scaling
MONSTER_LEVEL_INFANTRY_INITIAL_HEALTH            = 150
MONSTER_LEVEL_INFANTRY_ADDON_HEALTH              = 45
MONSTER_LEVEL_INFANTRY_INITIAL_POWER_ARMOR       = 100
MONSTER_LEVEL_INFANTRY_ADDON_POWER_ARMOR         = 13

-- Infantry Vanilla Level Scaling
MONSTER_LEVEL_INFANTRY_VANILLA_INITIAL_HEALTH    = 130
MONSTER_LEVEL_INFANTRY_VANILLA_ADDON_HEALTH      = 20
MONSTER_LEVEL_INFANTRY_VANILLA_INITIAL_ARMOR     = 50
MONSTER_LEVEL_INFANTRY_VANILLA_ADDON_ARMOR       = 15

-- Janitor Level Scaling
MONSTER_LEVEL_JANITOR_INITIAL_HEALTH             = 1075
MONSTER_LEVEL_JANITOR_ADDON_HEALTH               = 50
MONSTER_LEVEL_JANITOR_INITIAL_ARMOR              = 500
MONSTER_LEVEL_JANITOR_ADDON_ARMOR                = 100

-- Janitor2 Level Scaling
MONSTER_LEVEL_JANITOR2_INITIAL_HEALTH            = 880
MONSTER_LEVEL_JANITOR2_ADDON_HEALTH              = 50
MONSTER_LEVEL_JANITOR2_INITIAL_ARMOR             = 385
MONSTER_LEVEL_JANITOR2_ADDON_ARMOR               = 40

-- Jorg Small Level Scaling
MONSTER_LEVEL_JORG_SMALL_INITIAL_HEALTH          = 350
MONSTER_LEVEL_JORG_SMALL_ADDON_HEALTH            = 55
MONSTER_LEVEL_JORG_SMALL_INITIAL_ARMOR           = 50
MONSTER_LEVEL_JORG_SMALL_ADDON_ARMOR             = 20

-- Kamikaze Level Scaling
MONSTER_LEVEL_KAMIKAZE_INITIAL_HEALTH            = 50
MONSTER_LEVEL_KAMIKAZE_ADDON_HEALTH              = 10
MONSTER_LEVEL_KAMIKAZE_INITIAL_ARMOR             = 0
MONSTER_LEVEL_KAMIKAZE_ADDON_ARMOR               = 0

-- Makron Level Scaling
MONSTER_LEVEL_MAKRON_INITIAL_HEALTH              = 800
MONSTER_LEVEL_MAKRON_ADDON_HEALTH                = 100
MONSTER_LEVEL_MAKRON_INITIAL_POWER_ARMOR         = 250
MONSTER_LEVEL_MAKRON_ADDON_POWER_ARMOR           = 50

-- Medic Level Scaling
MONSTER_LEVEL_MEDIC_INITIAL_HEALTH               = 100
MONSTER_LEVEL_MEDIC_ADDON_HEALTH                 = 10
MONSTER_LEVEL_MEDIC_INITIAL_ARMOR                = 100
MONSTER_LEVEL_MEDIC_ADDON_ARMOR                  = 20

-- Medic Commander Level Scaling
MONSTER_LEVEL_MEDIC_COMMANDER_INITIAL_HEALTH     = 300
MONSTER_LEVEL_MEDIC_COMMANDER_ADDON_HEALTH       = 50
MONSTER_LEVEL_MEDIC_COMMANDER_INITIAL_ARMOR      = 0
MONSTER_LEVEL_MEDIC_COMMANDER_ADDON_ARMOR        = 0

-- Mutant Level Scaling
MONSTER_LEVEL_MUTANT_INITIAL_HEALTH              = 200
MONSTER_LEVEL_MUTANT_ADDON_HEALTH                = 85
MONSTER_LEVEL_MUTANT_INITIAL_ARMOR               = 0
MONSTER_LEVEL_MUTANT_ADDON_ARMOR                 = 0

-- Parasite Level Scaling
MONSTER_LEVEL_PARASITE_INITIAL_HEALTH            = 115
MONSTER_LEVEL_PARASITE_ADDON_HEALTH              = 25
MONSTER_LEVEL_PARASITE_INITIAL_ARMOR             = 0
MONSTER_LEVEL_PARASITE_ADDON_ARMOR               = 0

-- Perrokl Level Scaling
MONSTER_LEVEL_PERROKL_INITIAL_HEALTH             = 800
MONSTER_LEVEL_PERROKL_ADDON_HEALTH               = 100
MONSTER_LEVEL_PERROKL_INITIAL_ARMOR              = 0
MONSTER_LEVEL_PERROKL_ADDON_ARMOR                = 0

-- Psxarachnid Level Scaling
MONSTER_LEVEL_PSXARACHNID_INITIAL_HEALTH         = 600
MONSTER_LEVEL_PSXARACHNID_ADDON_HEALTH           = 60
MONSTER_LEVEL_PSXARACHNID_INITIAL_POWER_ARMOR    = 500
MONSTER_LEVEL_PSXARACHNID_ADDON_POWER_ARMOR      = 100

-- Redmutant Level Scaling
MONSTER_LEVEL_REDMUTANT_INITIAL_HEALTH           = 520
MONSTER_LEVEL_REDMUTANT_ADDON_HEALTH             = 90
MONSTER_LEVEL_REDMUTANT_INITIAL_ARMOR            = 0
MONSTER_LEVEL_REDMUTANT_ADDON_ARMOR              = 0

-- Runnertank Level Scaling
MONSTER_LEVEL_RUNNERTANK_INITIAL_HEALTH          = 850
MONSTER_LEVEL_RUNNERTANK_ADDON_HEALTH            = 80
MONSTER_LEVEL_RUNNERTANK_INITIAL_ARMOR           = 0
MONSTER_LEVEL_RUNNERTANK_ADDON_ARMOR             = 0

-- Shambler Level Scaling
MONSTER_LEVEL_SHAMBLER_INITIAL_HEALTH            = 950
MONSTER_LEVEL_SHAMBLER_ADDON_HEALTH              = 60
MONSTER_LEVEL_SHAMBLER_INITIAL_ARMOR             = 0
MONSTER_LEVEL_SHAMBLER_ADDON_ARMOR               = 0

-- Shambler Small Level Scaling
MONSTER_LEVEL_SHAMBLER_SMALL_INITIAL_HEALTH      = 350
MONSTER_LEVEL_SHAMBLER_SMALL_ADDON_HEALTH        = 50
MONSTER_LEVEL_SHAMBLER_SMALL_INITIAL_ARMOR       = 0
MONSTER_LEVEL_SHAMBLER_SMALL_ADDON_ARMOR         = 0

-- Shamblerkl Level Scaling
MONSTER_LEVEL_SHAMBLERKL_INITIAL_HEALTH          = 3800
MONSTER_LEVEL_SHAMBLERKL_ADDON_HEALTH            = 100
MONSTER_LEVEL_SHAMBLERKL_INITIAL_ARMOR           = 0
MONSTER_LEVEL_SHAMBLERKL_ADDON_ARMOR             = 0

-- Soldier Level Scaling
MONSTER_LEVEL_SOLDIER_INITIAL_HEALTH             = 50
MONSTER_LEVEL_SOLDIER_ADDON_HEALTH               = 15
MONSTER_LEVEL_SOLDIER_INITIAL_POWER_ARMOR        = 25
MONSTER_LEVEL_SOLDIER_ADDON_POWER_ARMOR          = 15

-- Soldier Hypergun Level Scaling
MONSTER_LEVEL_SOLDIER_HYPERGUN_INITIAL_HEALTH    = 95
MONSTER_LEVEL_SOLDIER_HYPERGUN_ADDON_HEALTH      = 15
MONSTER_LEVEL_SOLDIER_HYPERGUN_INITIAL_POWER_ARMOR = 40
MONSTER_LEVEL_SOLDIER_HYPERGUN_ADDON_POWER_ARMOR = 15

-- Soldier Lasergun Level Scaling
MONSTER_LEVEL_SOLDIER_LASERGUN_INITIAL_HEALTH    = 40
MONSTER_LEVEL_SOLDIER_LASERGUN_ADDON_HEALTH      = 10
MONSTER_LEVEL_SOLDIER_LASERGUN_INITIAL_POWER_ARMOR = 40
MONSTER_LEVEL_SOLDIER_LASERGUN_ADDON_POWER_ARMOR = 15

-- Soldier Light Level Scaling
MONSTER_LEVEL_SOLDIER_LIGHT_INITIAL_HEALTH       = 40
MONSTER_LEVEL_SOLDIER_LIGHT_ADDON_HEALTH         = 10
MONSTER_LEVEL_SOLDIER_LIGHT_INITIAL_POWER_ARMOR  = 20
MONSTER_LEVEL_SOLDIER_LIGHT_ADDON_POWER_ARMOR    = 10

-- Soldier Ripper Level Scaling
MONSTER_LEVEL_SOLDIER_RIPPER_INITIAL_HEALTH      = 70
MONSTER_LEVEL_SOLDIER_RIPPER_ADDON_HEALTH        = 15
MONSTER_LEVEL_SOLDIER_RIPPER_INITIAL_POWER_ARMOR = 40
MONSTER_LEVEL_SOLDIER_RIPPER_ADDON_POWER_ARMOR   = 15

-- Soldier Ss Level Scaling
MONSTER_LEVEL_SOLDIER_SS_INITIAL_HEALTH          = 40
MONSTER_LEVEL_SOLDIER_SS_ADDON_HEALTH            = 15
MONSTER_LEVEL_SOLDIER_SS_INITIAL_ARMOR           = 30
MONSTER_LEVEL_SOLDIER_SS_ADDON_ARMOR             = 15

-- Spider Level Scaling
MONSTER_LEVEL_SPIDER_INITIAL_HEALTH              = 550
MONSTER_LEVEL_SPIDER_ADDON_HEALTH                = 40
MONSTER_LEVEL_SPIDER_INITIAL_ARMOR               = 0
MONSTER_LEVEL_SPIDER_ADDON_ARMOR                 = 0

-- Stalker Level Scaling
MONSTER_LEVEL_STALKER_INITIAL_HEALTH             = 150
MONSTER_LEVEL_STALKER_ADDON_HEALTH               = 85
MONSTER_LEVEL_STALKER_INITIAL_ARMOR              = 0
MONSTER_LEVEL_STALKER_ADDON_ARMOR                = 0

-- Tank Level Scaling
MONSTER_LEVEL_TANK_INITIAL_HEALTH                = 630
MONSTER_LEVEL_TANK_ADDON_HEALTH                  = 40
MONSTER_LEVEL_TANK_INITIAL_ARMOR                 = 500
MONSTER_LEVEL_TANK_ADDON_ARMOR                   = 105

-- Tank 64 Level Scaling
MONSTER_LEVEL_TANK_64_INITIAL_HEALTH             = 1150
MONSTER_LEVEL_TANK_64_ADDON_HEALTH               = 80
MONSTER_LEVEL_TANK_64_INITIAL_ARMOR              = 750
MONSTER_LEVEL_TANK_64_ADDON_ARMOR                = 120

-- Tank Commander Level Scaling
MONSTER_LEVEL_TANK_COMMANDER_INITIAL_HEALTH      = 1000
MONSTER_LEVEL_TANK_COMMANDER_ADDON_HEALTH        = 60
MONSTER_LEVEL_TANK_COMMANDER_INITIAL_ARMOR       = 650
MONSTER_LEVEL_TANK_COMMANDER_ADDON_ARMOR         = 110

-- Tank Spawner Level Scaling
MONSTER_LEVEL_TANK_SPAWNER_INITIAL_HEALTH        = 475
MONSTER_LEVEL_TANK_SPAWNER_ADDON_HEALTH          = 50
MONSTER_LEVEL_TANK_SPAWNER_INITIAL_ARMOR         = 305
MONSTER_LEVEL_TANK_SPAWNER_ADDON_ARMOR           = 90

-- Turret Level Scaling
MONSTER_LEVEL_TURRET_INITIAL_HEALTH              = 100
MONSTER_LEVEL_TURRET_ADDON_HEALTH                = 20
MONSTER_LEVEL_TURRET_INITIAL_ARMOR               = 40
MONSTER_LEVEL_TURRET_ADDON_ARMOR                 = 15

-- Widow Level Scaling
MONSTER_LEVEL_WIDOW_INITIAL_HEALTH               = 1200
MONSTER_LEVEL_WIDOW_ADDON_HEALTH                 = 200
MONSTER_LEVEL_WIDOW_INITIAL_POWER_ARMOR          = 400
MONSTER_LEVEL_WIDOW_ADDON_POWER_ARMOR            = 100

-- Widow1 Level Scaling
MONSTER_LEVEL_WIDOW1_INITIAL_HEALTH              = 900
MONSTER_LEVEL_WIDOW1_ADDON_HEALTH                = 70
MONSTER_LEVEL_WIDOW1_INITIAL_POWER_ARMOR         = 380
MONSTER_LEVEL_WIDOW1_ADDON_POWER_ARMOR           = 40
